//! Markdown-driven persistent fact store for Oxcer agents.
//!
//! Mirrors Claude Code's `memory.md` pattern: facts are bullet lines in a
//! Markdown file that agents append to as they gather observations. On reload,
//! the Markdown is parsed back into structured [`Fact`] values.
//!
//! # File format
//!
//! ```markdown
//! # Oxcer Memory
//!
//! <!-- Auto-generated by Oxcer. Do not edit while agent is running. -->
//!
//! ## Facts
//!
//! - [2026-02-24T16:00:00Z] `file` Read src/main.rs: 42 lines, Rust entry point
//! - [2026-02-24T16:00:01Z] `dir` Workspace /src has 5 .rs files: main.rs, lib.rs, …
//! - [2026-02-24T16:00:02Z] `search` grep 'fn ' found 12 matches in src/
//! ```
//!
//! # Compaction
//!
//! When the fact count exceeds [`MAX_FACTS`], the oldest entries are dropped and
//! a `[compacted]` marker replaces them. This keeps the file bounded just as
//! Claude's memory compaction prunes stale context.

use std::fs;
use std::path::{Path, PathBuf};

use chrono::Utc;

// ── Limits ────────────────────────────────────────────────────────────────────

/// Maximum facts before compaction is triggered.
pub const MAX_FACTS: usize = 200;
/// Facts to keep after compaction (the most recent N).
const COMPACT_KEEP: usize = 100;
/// Maximum facts returned by a single [`Memory::query`] call.
const QUERY_MAX_RESULTS: usize = 10;

// ── Fact ──────────────────────────────────────────────────────────────────────

/// A single tagged observation recorded by an agent.
#[derive(Debug, Clone, PartialEq)]
pub struct Fact {
    /// ISO-8601 timestamp (`YYYY-MM-DDTHH:MM:SSZ`).
    pub timestamp: String,
    /// Short category tags (e.g. `["file", "dir"]`).
    pub tags: Vec<String>,
    /// Human-readable fact content.
    pub content: String,
}

impl Fact {
    /// Create a new fact timestamped now.
    pub fn new(content: impl Into<String>) -> Self {
        Fact {
            timestamp: Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string(),
            tags: Vec::new(),
            content: content.into(),
        }
    }

    /// Attach tags (builder pattern).
    pub fn with_tags(mut self, tags: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.tags = tags.into_iter().map(|t| t.into()).collect();
        self
    }

    /// Render as a Markdown bullet line.
    pub fn to_markdown_line(&self) -> String {
        if self.tags.is_empty() {
            format!("- [{}] {}", self.timestamp, self.content)
        } else {
            format!(
                "- [{}] `{}` {}",
                self.timestamp,
                self.tags.join("` `"),
                self.content
            )
        }
    }
}

// ── Memory ────────────────────────────────────────────────────────────────────

/// Persistent agent fact store.
///
/// Every [`append_fact`](Memory::append_fact) call immediately writes the
/// updated Markdown to disk so facts survive crashes.
pub struct Memory {
    /// Path to the `.md` file on disk. Use `/dev/null` (or any non-writable path)
    /// to suppress writes in tests.
    path: PathBuf,
    /// All recorded facts, oldest first.
    pub facts: Vec<Fact>,
}

impl Memory {
    // ── Constructors ──────────────────────────────────────────────────────────

    /// Load from `path` if it exists; otherwise start with an empty fact list.
    pub fn load_or_create(path: impl AsRef<Path>) -> Self {
        let path = path.as_ref().to_path_buf();
        let facts = if path.exists() {
            parse_markdown_facts(&fs::read_to_string(&path).unwrap_or_default())
        } else {
            Vec::new()
        };
        Memory { path, facts }
    }

    /// Create an in-memory (no-persist) instance. Useful in unit tests.
    pub fn in_memory() -> Self {
        Memory {
            path: PathBuf::from("/dev/null"),
            facts: Vec::new(),
        }
    }

    // ── Mutation ──────────────────────────────────────────────────────────────

    /// Append a fact, auto-derive tags from its content, and persist.
    ///
    /// Returns a reference to the newly appended fact.
    pub fn append_fact(&mut self, content: &str) -> &Fact {
        let tags = derive_tags(content);
        let fact = Fact::new(content).with_tags(tags);
        self.facts.push(fact);
        if self.facts.len() > MAX_FACTS {
            self.compact();
        }
        self.save();
        self.facts.last().unwrap()
    }

    // ── Query ─────────────────────────────────────────────────────────────────

    /// Keyword search over facts. Returns up to [`QUERY_MAX_RESULTS`] best matches.
    ///
    /// Scoring: count how many distinct keywords (≥3 chars) from `question`
    /// appear in the fact's content. Higher score = returned first.
    /// If `question` is empty or yields no keywords, returns the most-recent
    /// facts.
    pub fn query(&self, question: &str) -> Vec<&Fact> {
        let keywords: Vec<String> = question
            .split_whitespace()
            .map(|w| w.to_lowercase())
            .filter(|w| w.len() >= 3)
            .collect();

        if keywords.is_empty() {
            return self.facts.iter().rev().take(QUERY_MAX_RESULTS).collect();
        }

        let mut scored: Vec<(usize, &Fact)> = self
            .facts
            .iter()
            .map(|f| {
                let haystack = format!("{} {}", f.content.to_lowercase(), f.tags.join(" "));
                let score = keywords
                    .iter()
                    .filter(|kw| haystack.contains(kw.as_str()))
                    .count();
                (score, f)
            })
            .filter(|(s, _)| *s > 0)
            .collect();

        scored.sort_by(|a, b| b.0.cmp(&a.0));
        scored
            .into_iter()
            .take(QUERY_MAX_RESULTS)
            .map(|(_, f)| f)
            .collect()
    }

    /// Format relevant facts as a bracketed context block for LLM injection.
    ///
    /// Returns an empty string if no facts match `query`.
    pub fn as_context(&self, query: &str) -> String {
        let relevant = self.query(query);
        if relevant.is_empty() {
            return String::new();
        }
        let mut out = String::from("[MEMORY_CONTEXT]\n");
        for fact in relevant {
            out.push_str("• ");
            out.push_str(&fact.content);
            out.push('\n');
        }
        out.push_str("[/MEMORY_CONTEXT]");
        out
    }

    // ── private ───────────────────────────────────────────────────────────────

    /// Drop the oldest facts down to [`COMPACT_KEEP`] and insert a compaction
    /// marker so the history is auditable.
    fn compact(&mut self) {
        let total = self.facts.len();
        let keep_from = total - COMPACT_KEEP;
        let marker = format!(
            "[compacted] Dropped {} old facts on {}",
            keep_from,
            Utc::now().format("%Y-%m-%dT%H:%M:%SZ")
        );
        self.facts = self.facts.split_off(keep_from);
        self.facts.insert(0, Fact::new(marker).with_tags(["meta"]));
    }

    fn save(&self) {
        // Suppress writes if path is /dev/null (in-memory mode).
        if self.path == Path::new("/dev/null") {
            return;
        }
        if let Some(parent) = self.path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        let _ = fs::write(&self.path, to_markdown(&self.facts));
    }
}

// ── Serialisation helpers ─────────────────────────────────────────────────────

fn to_markdown(facts: &[Fact]) -> String {
    let mut out = String::from("# Oxcer Memory\n\n");
    out.push_str("<!-- Auto-generated by Oxcer. Do not edit while agent is running. -->\n\n");
    if facts.is_empty() {
        out.push_str("_No facts recorded yet._\n");
        return out;
    }
    out.push_str("## Facts\n\n");
    for fact in facts {
        out.push_str(&fact.to_markdown_line());
        out.push('\n');
    }
    out
}

fn parse_markdown_facts(content: &str) -> Vec<Fact> {
    let mut facts = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        // Pattern: `- [timestamp] <optional `tag` ...> content`
        let rest = match line.strip_prefix("- [") {
            Some(r) => r,
            None => continue,
        };
        let bracket_end = match rest.find(']') {
            Some(i) => i,
            None => continue,
        };
        let timestamp = rest[..bracket_end].to_string();
        let after = rest[bracket_end + 1..].trim();
        let (tags, content_str) = split_leading_tags(after);
        facts.push(Fact {
            timestamp,
            tags,
            content: content_str,
        });
    }
    facts
}

/// Parse leading `` `tag` `` tokens from a string like `` `file` `dir` Some content ``.
fn split_leading_tags(s: &str) -> (Vec<String>, String) {
    let mut tags = Vec::new();
    let mut rest = s;
    loop {
        let trimmed = rest.trim_start();
        if let Some(inner) = trimmed.strip_prefix('`') {
            if let Some(close) = inner.find('`') {
                tags.push(inner[..close].to_string());
                rest = inner[close + 1..].trim_start();
                continue;
            }
        }
        break;
    }
    (tags, rest.to_string())
}

/// Infer tags from fact content by keyword matching.
fn derive_tags(content: &str) -> Vec<String> {
    let lower = content.to_lowercase();
    let mut tags = Vec::new();

    if lower.contains("read ") || lower.contains("file:") || has_file_ext(&lower) {
        tags.push("file".to_string());
    }
    if lower.contains("list ")
        || lower.contains("directory")
        || lower.contains("folder")
        || lower.contains("glob")
        || lower.contains("explore")
    {
        tags.push("dir".to_string());
    }
    if lower.contains("search") || lower.contains("grep") || lower.contains("pattern") {
        tags.push("search".to_string());
    }
    if lower.contains("summary")
        || lower.contains("summarize")
        || lower.contains("lines")
        || lower.contains("answer")
    {
        tags.push("summary".to_string());
    }
    tags
}

fn has_file_ext(lower: &str) -> bool {
    const EXTS: &[&str] = &[
        ".rs", ".swift", ".py", ".ts", ".js", ".md", ".toml", ".json", ".yaml",
        ".yml", ".txt", ".sh", ".csv", ".pdf", ".docx",
    ];
    EXTS.iter().any(|ext| lower.contains(ext))
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Basic operations ──────────────────────────────────────────────────────

    #[test]
    fn append_and_count() {
        let mut mem = Memory::in_memory();
        mem.append_fact("First fact about main.rs");
        mem.append_fact("Second fact about Cargo.toml");
        assert_eq!(mem.facts.len(), 2);
    }

    #[test]
    fn query_returns_relevant_facts() {
        let mut mem = Memory::in_memory();
        mem.append_fact("Read main.rs: 120 lines, Rust entry point");
        mem.append_fact("Workspace has 5 .rs files: main.rs, lib.rs");
        mem.append_fact("Today is sunny and warm");

        let results = mem.query("main.rs summary");
        assert!(!results.is_empty(), "should find matching facts");
        // Most relevant should mention main.rs
        assert!(
            results[0].content.contains("main.rs"),
            "top result: {}",
            results[0].content
        );
        // Weather fact should not appear
        let contents: Vec<_> = results.iter().map(|f| f.content.as_str()).collect();
        assert!(
            !contents.contains(&"Today is sunny and warm"),
            "irrelevant fact leaked in"
        );
    }

    #[test]
    fn query_empty_string_returns_recent() {
        let mut mem = Memory::in_memory();
        for i in 0..5 {
            mem.append_fact(&format!("fact {}", i));
        }
        let results = mem.query("");
        assert!(!results.is_empty());
        assert!(results.len() <= 10);
    }

    #[test]
    fn query_no_keyword_match_returns_empty() {
        let mut mem = Memory::in_memory();
        mem.append_fact("Read main.rs: entry point");
        let results = mem.query("xyzzy_does_not_exist");
        assert!(results.is_empty());
    }

    // ── as_context ────────────────────────────────────────────────────────────

    #[test]
    fn as_context_wraps_in_block() {
        let mut mem = Memory::in_memory();
        mem.append_fact("Read main.rs: 42 lines");
        let ctx = mem.as_context("main.rs");
        assert!(ctx.starts_with("[MEMORY_CONTEXT]"), "got: {ctx}");
        assert!(ctx.contains("• Read main.rs"), "got: {ctx}");
        assert!(ctx.ends_with("[/MEMORY_CONTEXT]"), "got: {ctx}");
    }

    #[test]
    fn as_context_empty_when_no_match() {
        let mem = Memory::in_memory();
        let ctx = mem.as_context("something");
        assert!(ctx.is_empty(), "got: {ctx}");
    }

    // ── Markdown round-trip ───────────────────────────────────────────────────

    #[test]
    fn markdown_round_trip() {
        let mut mem = Memory::in_memory();
        mem.append_fact("Fact alpha");
        mem.append_fact("Fact beta");

        let md = to_markdown(&mem.facts);
        let parsed = parse_markdown_facts(&md);

        assert_eq!(parsed.len(), 2, "should round-trip 2 facts");
        assert_eq!(parsed[0].content, "Fact alpha");
        assert_eq!(parsed[1].content, "Fact beta");
    }

    #[test]
    fn markdown_round_trip_with_tags() {
        let fact = Fact::new("Read src/main.rs").with_tags(["file", "summary"]);
        let line = fact.to_markdown_line();
        // Verify it parses back correctly
        let (tags, content) = split_leading_tags(
            line.strip_prefix("- [")
                .and_then(|s| s.find(']').map(|i| s[i + 2..].trim_start()))
                .unwrap_or(""),
        );
        assert_eq!(tags, vec!["file", "summary"]);
        assert_eq!(content, "Read src/main.rs");
    }

    #[test]
    fn persist_and_reload() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("memory.md");
        {
            let mut mem = Memory::load_or_create(&path);
            mem.append_fact("Persisted fact one");
            mem.append_fact("Persisted fact two");
        }
        let mem2 = Memory::load_or_create(&path);
        assert_eq!(mem2.facts.len(), 2, "should reload 2 facts");
        assert_eq!(mem2.facts[0].content, "Persisted fact one");
        assert_eq!(mem2.facts[1].content, "Persisted fact two");
    }

    // ── Compaction ────────────────────────────────────────────────────────────

    #[test]
    fn compact_triggered_at_max_facts() {
        let mut mem = Memory::in_memory();
        for i in 0..=MAX_FACTS {
            mem.append_fact(&format!("fact {}", i));
        }
        // After compaction: COMPACT_KEEP recent facts + 1 compaction marker
        assert!(
            mem.facts.len() <= COMPACT_KEEP + 2,
            "expected ≤{} facts after compaction, got {}",
            COMPACT_KEEP + 2,
            mem.facts.len()
        );
        // Most recent fact should still be present
        assert!(
            mem.facts
                .iter()
                .any(|f| f.content.contains(&format!("fact {}", MAX_FACTS))),
            "most recent fact should survive compaction"
        );
    }

    // ── Tag derivation ────────────────────────────────────────────────────────

    #[test]
    fn derive_tags_file() {
        let tags = derive_tags("Read src/main.rs: 120 lines");
        assert!(tags.contains(&"file".to_string()), "tags: {tags:?}");
    }

    #[test]
    fn derive_tags_directory() {
        let tags = derive_tags("Explore: found 5 files in directory");
        assert!(tags.contains(&"dir".to_string()), "tags: {tags:?}");
    }

    #[test]
    fn split_leading_tags_handles_multiple() {
        let (tags, content) = split_leading_tags("`file` `dir` Some content here");
        assert_eq!(tags, vec!["file", "dir"]);
        assert_eq!(content, "Some content here");
    }

    #[test]
    fn split_leading_tags_no_tags() {
        let (tags, content) = split_leading_tags("Plain content");
        assert!(tags.is_empty());
        assert_eq!(content, "Plain content");
    }
}
