// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(oxcer_ffiFFI)
import oxcer_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_oxcer_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_oxcer_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct AgentRequestPayload {
    public var taskDescription: String
    public var workspaceId: String?
    public var workspaceRoot: String?
    public var context: TaskContext?
    public var appConfigDir: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(taskDescription: String, workspaceId: String?, workspaceRoot: String?, context: TaskContext?, appConfigDir: String?) {
        self.taskDescription = taskDescription
        self.workspaceId = workspaceId
        self.workspaceRoot = workspaceRoot
        self.context = context
        self.appConfigDir = appConfigDir
    }
}



extension AgentRequestPayload: Equatable, Hashable {
    public static func ==(lhs: AgentRequestPayload, rhs: AgentRequestPayload) -> Bool {
        if lhs.taskDescription != rhs.taskDescription {
            return false
        }
        if lhs.workspaceId != rhs.workspaceId {
            return false
        }
        if lhs.workspaceRoot != rhs.workspaceRoot {
            return false
        }
        if lhs.context != rhs.context {
            return false
        }
        if lhs.appConfigDir != rhs.appConfigDir {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(taskDescription)
        hasher.combine(workspaceId)
        hasher.combine(workspaceRoot)
        hasher.combine(context)
        hasher.combine(appConfigDir)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgentRequestPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgentRequestPayload {
        return
            try AgentRequestPayload(
                taskDescription: FfiConverterString.read(from: &buf), 
                workspaceId: FfiConverterOptionString.read(from: &buf), 
                workspaceRoot: FfiConverterOptionString.read(from: &buf), 
                context: FfiConverterOptionTypeTaskContext.read(from: &buf), 
                appConfigDir: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AgentRequestPayload, into buf: inout [UInt8]) {
        FfiConverterString.write(value.taskDescription, into: &buf)
        FfiConverterOptionString.write(value.workspaceId, into: &buf)
        FfiConverterOptionString.write(value.workspaceRoot, into: &buf)
        FfiConverterOptionTypeTaskContext.write(value.context, into: &buf)
        FfiConverterOptionString.write(value.appConfigDir, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentRequestPayload_lift(_ buf: RustBuffer) throws -> AgentRequestPayload {
    return try FfiConverterTypeAgentRequestPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentRequestPayload_lower(_ value: AgentRequestPayload) -> RustBuffer {
    return FfiConverterTypeAgentRequestPayload.lower(value)
}


public struct AgentResponse {
    public var ok: Bool
    public var answer: String?
    public var error: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ok: Bool, answer: String?, error: String?) {
        self.ok = ok
        self.answer = answer
        self.error = error
    }
}



extension AgentResponse: Equatable, Hashable {
    public static func ==(lhs: AgentResponse, rhs: AgentResponse) -> Bool {
        if lhs.ok != rhs.ok {
            return false
        }
        if lhs.answer != rhs.answer {
            return false
        }
        if lhs.error != rhs.error {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ok)
        hasher.combine(answer)
        hasher.combine(error)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgentResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgentResponse {
        return
            try AgentResponse(
                ok: FfiConverterBool.read(from: &buf), 
                answer: FfiConverterOptionString.read(from: &buf), 
                error: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AgentResponse, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.ok, into: &buf)
        FfiConverterOptionString.write(value.answer, into: &buf)
        FfiConverterOptionString.write(value.error, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentResponse_lift(_ buf: RustBuffer) throws -> AgentResponse {
    return try FfiConverterTypeAgentResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentResponse_lower(_ value: AgentResponse) -> RustBuffer {
    return FfiConverterTypeAgentResponse.lower(value)
}


public struct LogEvent {
    public var timestamp: String
    public var sessionId: String
    public var requestId: String?
    public var caller: String
    public var component: String
    public var action: String
    public var decision: String?
    public var metrics: LogMetrics
    /**
     * JSON string for arbitrary details (Swift decodes to AnyCodableValue).
     */
    public var details: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(timestamp: String, sessionId: String, requestId: String?, caller: String, component: String, action: String, decision: String?, metrics: LogMetrics, 
        /**
         * JSON string for arbitrary details (Swift decodes to AnyCodableValue).
         */details: String?) {
        self.timestamp = timestamp
        self.sessionId = sessionId
        self.requestId = requestId
        self.caller = caller
        self.component = component
        self.action = action
        self.decision = decision
        self.metrics = metrics
        self.details = details
    }
}



extension LogEvent: Equatable, Hashable {
    public static func ==(lhs: LogEvent, rhs: LogEvent) -> Bool {
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.requestId != rhs.requestId {
            return false
        }
        if lhs.caller != rhs.caller {
            return false
        }
        if lhs.component != rhs.component {
            return false
        }
        if lhs.action != rhs.action {
            return false
        }
        if lhs.decision != rhs.decision {
            return false
        }
        if lhs.metrics != rhs.metrics {
            return false
        }
        if lhs.details != rhs.details {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(timestamp)
        hasher.combine(sessionId)
        hasher.combine(requestId)
        hasher.combine(caller)
        hasher.combine(component)
        hasher.combine(action)
        hasher.combine(decision)
        hasher.combine(metrics)
        hasher.combine(details)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLogEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LogEvent {
        return
            try LogEvent(
                timestamp: FfiConverterString.read(from: &buf), 
                sessionId: FfiConverterString.read(from: &buf), 
                requestId: FfiConverterOptionString.read(from: &buf), 
                caller: FfiConverterString.read(from: &buf), 
                component: FfiConverterString.read(from: &buf), 
                action: FfiConverterString.read(from: &buf), 
                decision: FfiConverterOptionString.read(from: &buf), 
                metrics: FfiConverterTypeLogMetrics.read(from: &buf), 
                details: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: LogEvent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.timestamp, into: &buf)
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterOptionString.write(value.requestId, into: &buf)
        FfiConverterString.write(value.caller, into: &buf)
        FfiConverterString.write(value.component, into: &buf)
        FfiConverterString.write(value.action, into: &buf)
        FfiConverterOptionString.write(value.decision, into: &buf)
        FfiConverterTypeLogMetrics.write(value.metrics, into: &buf)
        FfiConverterOptionString.write(value.details, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogEvent_lift(_ buf: RustBuffer) throws -> LogEvent {
    return try FfiConverterTypeLogEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogEvent_lower(_ value: LogEvent) -> RustBuffer {
    return FfiConverterTypeLogEvent.lower(value)
}


public struct LogMetrics {
    public var tokensIn: UInt32?
    public var tokensOut: UInt32?
    public var latencyMs: UInt64?
    public var costUsd: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(tokensIn: UInt32?, tokensOut: UInt32?, latencyMs: UInt64?, costUsd: Double?) {
        self.tokensIn = tokensIn
        self.tokensOut = tokensOut
        self.latencyMs = latencyMs
        self.costUsd = costUsd
    }
}



extension LogMetrics: Equatable, Hashable {
    public static func ==(lhs: LogMetrics, rhs: LogMetrics) -> Bool {
        if lhs.tokensIn != rhs.tokensIn {
            return false
        }
        if lhs.tokensOut != rhs.tokensOut {
            return false
        }
        if lhs.latencyMs != rhs.latencyMs {
            return false
        }
        if lhs.costUsd != rhs.costUsd {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tokensIn)
        hasher.combine(tokensOut)
        hasher.combine(latencyMs)
        hasher.combine(costUsd)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLogMetrics: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LogMetrics {
        return
            try LogMetrics(
                tokensIn: FfiConverterOptionUInt32.read(from: &buf), 
                tokensOut: FfiConverterOptionUInt32.read(from: &buf), 
                latencyMs: FfiConverterOptionUInt64.read(from: &buf), 
                costUsd: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: LogMetrics, into buf: inout [UInt8]) {
        FfiConverterOptionUInt32.write(value.tokensIn, into: &buf)
        FfiConverterOptionUInt32.write(value.tokensOut, into: &buf)
        FfiConverterOptionUInt64.write(value.latencyMs, into: &buf)
        FfiConverterOptionDouble.write(value.costUsd, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogMetrics_lift(_ buf: RustBuffer) throws -> LogMetrics {
    return try FfiConverterTypeLogMetrics.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogMetrics_lower(_ value: LogMetrics) -> RustBuffer {
    return FfiConverterTypeLogMetrics.lower(value)
}


public struct SessionSummary {
    public var sessionId: String
    public var startTimestamp: String
    public var endTimestamp: String
    public var totalCostUsd: Double
    public var success: Bool
    public var toolCallsCount: UInt32
    public var approvalsCount: UInt32
    public var deniesCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionId: String, startTimestamp: String, endTimestamp: String, totalCostUsd: Double, success: Bool, toolCallsCount: UInt32, approvalsCount: UInt32, deniesCount: UInt32) {
        self.sessionId = sessionId
        self.startTimestamp = startTimestamp
        self.endTimestamp = endTimestamp
        self.totalCostUsd = totalCostUsd
        self.success = success
        self.toolCallsCount = toolCallsCount
        self.approvalsCount = approvalsCount
        self.deniesCount = deniesCount
    }
}



extension SessionSummary: Equatable, Hashable {
    public static func ==(lhs: SessionSummary, rhs: SessionSummary) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.startTimestamp != rhs.startTimestamp {
            return false
        }
        if lhs.endTimestamp != rhs.endTimestamp {
            return false
        }
        if lhs.totalCostUsd != rhs.totalCostUsd {
            return false
        }
        if lhs.success != rhs.success {
            return false
        }
        if lhs.toolCallsCount != rhs.toolCallsCount {
            return false
        }
        if lhs.approvalsCount != rhs.approvalsCount {
            return false
        }
        if lhs.deniesCount != rhs.deniesCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(startTimestamp)
        hasher.combine(endTimestamp)
        hasher.combine(totalCostUsd)
        hasher.combine(success)
        hasher.combine(toolCallsCount)
        hasher.combine(approvalsCount)
        hasher.combine(deniesCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionSummary {
        return
            try SessionSummary(
                sessionId: FfiConverterString.read(from: &buf), 
                startTimestamp: FfiConverterString.read(from: &buf), 
                endTimestamp: FfiConverterString.read(from: &buf), 
                totalCostUsd: FfiConverterDouble.read(from: &buf), 
                success: FfiConverterBool.read(from: &buf), 
                toolCallsCount: FfiConverterUInt32.read(from: &buf), 
                approvalsCount: FfiConverterUInt32.read(from: &buf), 
                deniesCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SessionSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterString.write(value.startTimestamp, into: &buf)
        FfiConverterString.write(value.endTimestamp, into: &buf)
        FfiConverterDouble.write(value.totalCostUsd, into: &buf)
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterUInt32.write(value.toolCallsCount, into: &buf)
        FfiConverterUInt32.write(value.approvalsCount, into: &buf)
        FfiConverterUInt32.write(value.deniesCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionSummary_lift(_ buf: RustBuffer) throws -> SessionSummary {
    return try FfiConverterTypeSessionSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionSummary_lower(_ value: SessionSummary) -> RustBuffer {
    return FfiConverterTypeSessionSummary.lower(value)
}


public struct TaskContext {
    public var workspaceId: String?
    public var selectedPaths: [String]?
    public var riskHints: Bool?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(workspaceId: String?, selectedPaths: [String]?, riskHints: Bool?) {
        self.workspaceId = workspaceId
        self.selectedPaths = selectedPaths
        self.riskHints = riskHints
    }
}



extension TaskContext: Equatable, Hashable {
    public static func ==(lhs: TaskContext, rhs: TaskContext) -> Bool {
        if lhs.workspaceId != rhs.workspaceId {
            return false
        }
        if lhs.selectedPaths != rhs.selectedPaths {
            return false
        }
        if lhs.riskHints != rhs.riskHints {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(workspaceId)
        hasher.combine(selectedPaths)
        hasher.combine(riskHints)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskContext: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskContext {
        return
            try TaskContext(
                workspaceId: FfiConverterOptionString.read(from: &buf), 
                selectedPaths: FfiConverterOptionSequenceString.read(from: &buf), 
                riskHints: FfiConverterOptionBool.read(from: &buf)
        )
    }

    public static func write(_ value: TaskContext, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.workspaceId, into: &buf)
        FfiConverterOptionSequenceString.write(value.selectedPaths, into: &buf)
        FfiConverterOptionBool.write(value.riskHints, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskContext_lift(_ buf: RustBuffer) throws -> TaskContext {
    return try FfiConverterTypeTaskContext.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskContext_lower(_ value: TaskContext) -> RustBuffer {
    return FfiConverterTypeTaskContext.lower(value)
}


public struct WorkspaceInfo {
    public var id: String
    public var name: String
    public var rootPath: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, rootPath: String) {
        self.id = id
        self.name = name
        self.rootPath = rootPath
    }
}



extension WorkspaceInfo: Equatable, Hashable {
    public static func ==(lhs: WorkspaceInfo, rhs: WorkspaceInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.rootPath != rhs.rootPath {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(rootPath)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceInfo {
        return
            try WorkspaceInfo(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                rootPath: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WorkspaceInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.rootPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceInfo_lift(_ buf: RustBuffer) throws -> WorkspaceInfo {
    return try FfiConverterTypeWorkspaceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceInfo_lower(_ value: WorkspaceInfo) -> RustBuffer {
    return FfiConverterTypeWorkspaceInfo.lower(value)
}


public enum OxcerError {

    
    
    case Generic(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOxcerError: FfiConverterRustBuffer {
    typealias SwiftType = OxcerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OxcerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OxcerError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Generic(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


extension OxcerError: Equatable, Hashable {}

extension OxcerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




public protocol DownloadCallback : AnyObject {
    
    /**
     * Progress from 0.0 to 1.0. Message is a user-friendly status.
     */
    func onProgress(progress: Double, message: String) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceDownloadCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceDownloadCallback = UniffiVTableCallbackInterfaceDownloadCallback(
        onProgress: { (
            uniffiHandle: UInt64,
            progress: Double,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceDownloadCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     progress: try FfiConverterDouble.lift(progress),
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceDownloadCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface DownloadCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitDownloadCallback() {
    uniffi_oxcer_ffi_fn_init_callback_vtable_downloadcallback(&UniffiCallbackInterfaceDownloadCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceDownloadCallback {
    fileprivate static var handleMap = UniffiHandleMap<DownloadCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceDownloadCallback : FfiConverter {
    typealias SwiftType = DownloadCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTaskContext: FfiConverterRustBuffer {
    typealias SwiftType = TaskContext?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTaskContext.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTaskContext.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLogEvent: FfiConverterRustBuffer {
    typealias SwiftType = [LogEvent]

    public static func write(_ value: [LogEvent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLogEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LogEvent] {
        let len: Int32 = try readInt(&buf)
        var seq = [LogEvent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLogEvent.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSessionSummary: FfiConverterRustBuffer {
    typealias SwiftType = [SessionSummary]

    public static func write(_ value: [SessionSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSessionSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SessionSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [SessionSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSessionSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkspaceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [WorkspaceInfo]

    public static func write(_ value: [WorkspaceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkspaceInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WorkspaceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [WorkspaceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkspaceInfo.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Ensure the local model FILES are present (download if needed). Does NOT load the engine.
 * Engine is loaded lazily on first inference (generate_text). Call at startup before inference.
 * Safe to call multiple times; subsequent calls no-op if files already ensured.
 */
public func ensureLocalModel(appConfigDir: String, callback: DownloadCallback)async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oxcer_ffi_fn_func_ensure_local_model(FfiConverterString.lower(appConfigDir),FfiConverterCallbackInterfaceDownloadCallback.lower(callback)
                )
            },
            pollFunc: ffi_oxcer_ffi_rust_future_poll_void,
            completeFunc: ffi_oxcer_ffi_rust_future_complete_void,
            freeFunc: ffi_oxcer_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeOxcerError.lift
        )
}
/**
 * Generate text using the global model. Loads engine lazily on first call (requires ensure_local_model first).
 *
 * # Lazy Load + Zero-Copy Arc Pattern
 * 1. get_or_init_engine() loads engine on first use (heavy allocation deferred from startup).
 * 2. Clone the Arc — cost: refcount increment, NOT a copy of the 2.3GB model.
 * 3. Move the Arc pointer into the thread; heap data stays put.
 */
public func generateText(prompt: String)async throws  -> String {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oxcer_ffi_fn_func_generate_text(FfiConverterString.lower(prompt)
                )
            },
            pollFunc: ffi_oxcer_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_oxcer_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_oxcer_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeOxcerError.lift
        )
}
/**
 * List recent sessions from the app config directory.
 */
public func listSessions(appConfigDir: String)throws  -> [SessionSummary] {
    return try  FfiConverterSequenceTypeSessionSummary.lift(try rustCallWithError(FfiConverterTypeOxcerError.lift) {
    uniffi_oxcer_ffi_fn_func_list_sessions(
        FfiConverterString.lower(appConfigDir),$0
    )
})
}
/**
 * List workspaces from config.json in the given app config directory.
 * Returns an empty vec if config.json is absent. Propagates I/O and parse errors.
 */
public func listWorkspaces(appConfigDir: String)throws  -> [WorkspaceInfo] {
    return try  FfiConverterSequenceTypeWorkspaceInfo.lift(try rustCallWithError(FfiConverterTypeOxcerError.lift) {
    uniffi_oxcer_ffi_fn_func_list_workspaces(
        FfiConverterString.lower(appConfigDir),$0
    )
})
}
/**
 * Load session log events for one session.
 * Bounded at MAX_EVENTS_PER_SESSION_LOG (2000) by telemetry layer; returns latest events.
 */
public func loadSessionLog(sessionId: String, appConfigDir: String)throws  -> [LogEvent] {
    return try  FfiConverterSequenceTypeLogEvent.lift(try rustCallWithError(FfiConverterTypeOxcerError.lift) {
    uniffi_oxcer_ffi_fn_func_load_session_log(
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(appConfigDir),$0
    )
})
}
/**
 * Zero-cost FFI warm-up. Triggers dylib load and static runtime initialization
 * without executing any heavy LLM logic. Call at app launch to pay the VMS cost upfront.
 */
public func ping() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_oxcer_ffi_fn_func_ping($0
    )
})
}
/**
 * Run the agent task (stub executor; tools/approvals require app step API).
 *
 * # Singleton enforcement
 * The agent uses `FfiStubExecutor` which does not invoke the LLM. When a real executor is wired,
 * it MUST use `GLOBAL_ENGINE` for LlmGenerate intents — never create new engine instances.
 * Heavy orchestrator work runs on a dedicated blocking thread pool; does not block the caller's executor.
 */
public func runAgentTask(payload: AgentRequestPayload)async throws  -> AgentResponse {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oxcer_ffi_fn_func_run_agent_task(FfiConverterTypeAgentRequestPayload.lower(payload)
                )
            },
            pollFunc: ffi_oxcer_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_oxcer_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_oxcer_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeAgentResponse.lift,
            errorHandler: FfiConverterTypeOxcerError.lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_oxcer_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_ensure_local_model() != 36503) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_generate_text() != 56309) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_list_sessions() != 38949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_list_workspaces() != 1311) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_load_session_log() != 14285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_ping() != 10669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_func_run_agent_task() != 20394) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oxcer_ffi_checksum_method_downloadcallback_on_progress() != 23691) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDownloadCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all